name: Pull Request Node Version Bumper
author: Mitchell Simoens
description: Automatically bump a temporary alpha version of a node module within a pull request
branding:
  color: red
  icon: git-pull-request
inputs:
  cwd:
    default: ./
    description: Set to the relative path where the package.json is located in.
    required: false
  skip_git_tag:
    description: Set to not create a git tag when npm version command is run.
    required: false
outputs:
  new_version:
    description: The new version that was pushed.
runs:
  using: docker
  image: Dockerfile
